version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --tcp-keepalive=10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis