version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --timeout 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis